<a href="https://colab.research.google.com/github/handelenriquezacuna/IntroDataScience/blob/main/IntroTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
1+1

2

In [ ]:
import numpy as np
import torch

In [ ]:
# Lista de python convertida a tensor
x = torch.tensor([1,2,3,4,5])
print(x)


tensor([1, 2, 3, 4, 5])


In [ ]:
# Vector de rango de numeros
vectorIncrimental = torch.arange(0,5,0.1)
print(vectorIncrimental)

tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000, 1.1000, 1.2000, 1.3000, 1.4000, 1.5000, 1.6000, 1.7000,
        1.8000, 1.9000, 2.0000, 2.1000, 2.2000, 2.3000, 2.4000, 2.5000, 2.6000,
        2.7000, 2.8000, 2.9000, 3.0000, 3.1000, 3.2000, 3.3000, 3.4000, 3.5000,
        3.6000, 3.7000, 3.8000, 3.9000, 4.0000, 4.1000, 4.2000, 4.3000, 4.4000,
        4.5000, 4.6000, 4.7000, 4.8000, 4.9000])


In [ ]:
print("Tamaño Vector", vectorIncrimental.shape)

Tamaño Vector torch.Size([50])


In [ ]:
# Operaciones con vectores
escalar = 10
vector = torch.tensor([1,2,3,4,5])
print(f"Valor escalar es {escalar} y el valor del vector es {vector}")
print("Resultado de la operacion de multiplicar es: ", escalar*vector)

Valor escalar es 10 y el valor del vector es tensor([1, 2, 3, 4, 5])
Resultado de la operacion de multiplicar es:  tensor([10, 20, 30, 40, 50])


In [ ]:
# Suma de vectores
vector1 = torch.tensor([1,2,3,4,5])
vector2 = torch.tensor([10,9,8,7,6])

print("Vector 1: ", vector1)
print("Vector 2: ", vector2)
print("Resultado de la suma de vectores es: ", vector1+vector2)

# Resta de vectores
print("Resultado de la resta de vectores es: ", vector1-vector2)

Vector 1:  tensor([1, 2, 3, 4, 5])
Vector 2:  tensor([10,  9,  8,  7,  6])
Resultado de la suma de vectores es:  tensor([11, 11, 11, 11, 11])
Resultado de la resta de vectores es:  tensor([-9, -7, -5, -3, -1])


In [ ]:
# Suma Torch add
sumTorch = torch.add(vector1, vector2)
print("Resultado de la suma de vectores con torch.add es: ", sumTorch)
# Resta Torch sub
subTorch = torch.sub(vector1, vector2)
print("Resultado de la resta de vectores con torch.sub es: ", subTorch)

Resultado de la suma de vectores con torch.add es:  tensor([11, 11, 11, 11, 11])
Resultado de la resta de vectores con torch.sub es:  tensor([-9, -7, -5, -3, -1])


In [ ]:
# Producto escalar torch dot
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([10,20])
print("Vector 1: ", vector1)
print("Vector 2: ", vector2)
productoEscalar = torch.dot(vector1, vector2)
print("Resultado del producto escalar es: ", productoEscalar)

Vector 1:  tensor([1, 2])
Vector 2:  tensor([10, 20])
Resultado del producto escalar es:  tensor(50)


In [ ]:
# Matrices
matriz = torch.tensor([[1,2],[3,4],[5,4]])
print(matriz)
matriz2 = torch.tensor([[10,20],[30,40],[50,40]])
print(matriz2)
sumMatriz = matriz + matriz2
print("Resultado de la suma de matrices es: ", sumMatriz)
# sum matriz torch
sumMatrizTorch = torch.add(matriz, matriz2)
print("Resultado de la suma de matrices con torch.add es: ", sumMatrizTorch)

tensor([[1, 2],
        [3, 4],
        [5, 4]])
tensor([[10, 20],
        [30, 40],
        [50, 40]])
Resultado de la suma de matrices es:  tensor([[11, 22],
        [33, 44],
        [55, 44]])
Resultado de la suma de matrices con torch.add es:  tensor([[11, 22],
        [33, 44],
        [55, 44]])


In [ ]:
# Resta Matrices
subMatriz = matriz - matriz2
print("Resultado de la resta de matrices es: ", subMatriz)
# sub matriz torch
subMatrizTorch = torch.sub(matriz, matriz2)
print("Resultado de la resta de matrices con torch.sub es: ", subMatrizTorch)

Resultado de la resta de matrices es:  tensor([[ -9, -18],
        [-27, -36],
        [-45, -36]])
Resultado de la resta de matrices con torch.sub es:  tensor([[ -9, -18],
        [-27, -36],
        [-45, -36]])


In [ ]:
# Multiplicacion de matrices
multMatriz = matriz * matriz2
print("Resultado de la multiplicacion de matrices es: ", multMatriz)
# mult matriz torch
multMatrizTorch = torch.mul(matriz, matriz2)
print("Resultado de la multiplicacion de matrices con torch.mul es: ", multMatrizTorch)

Resultado de la multiplicacion de matrices es:  tensor([[ 10,  40],
        [ 90, 160],
        [250, 160]])
Resultado de la multiplicacion de matrices con torch.mul es:  tensor([[ 10,  40],
        [ 90, 160],
        [250, 160]])


In [ ]:
# Division de matrices
divMatriz = matriz / matriz2
print("Resultado de la division de matrices es: ", divMatriz)
# div matriz torch
divMatrizTorch = torch.div(matriz, matriz2)
print("Resultado de la division de matrices con torch.div es: ", divMatrizTorch)

Resultado de la division de matrices es:  tensor([[0.1000, 0.1000],
        [0.1000, 0.1000],
        [0.1000, 0.1000]])
Resultado de la division de matrices con torch.div es:  tensor([[0.1000, 0.1000],
        [0.1000, 0.1000],
        [0.1000, 0.1000]])
